name: local_storage_sqflite
description: "A flutter project demonstrating local storage using sqflite"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  # Below would allow us to work with sqlite database.
  sqflite: ^2.4.2
  # Below would allow us to perform path manipulations, which we would use to combine file names and paths.
  # so that we have a place where we can access or store our database file.
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true